modules:
  - name: DemoApp
    path: App
    excludedFiles:
        - __generated__/FakeGenerated.swift
  - name: NetworkClient
    path: Libraries/NetworkClient/NetworkClient
    excludedFiles:
        - __generated__/FakeGenerated.swift
